version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/proxy/certs:/etc/nginx/certs:ro
      - ~/proxy/vhostd:/etc/nginx/vhost.d
      - ~/proxy/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ~/letsencrypt/certs:/etc/nginx/certs:rw
      - ~/letsencrypt/vhostd:/etc/nginx/vhost.d
      - ~/letsencrypt/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ~/portfolio/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=jhoacar.me, www.jhoacar.me
      - LETSENCRYPT_HOST=jhoacar.me, www.jhoacar.me
      - LETSENCRYPT_EMAIL=carrerojhoan@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt
