import "../styles/styles.scss";


import Head from 'next/head';

function Portfolio({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default Portfolio;
