on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: deploy
jobs:
  build-push-deploy:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Files of Github
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push the latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:v1.0.${{ github.run_number }},${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:latest
      - 
        name: Copy docker-compose file via SSH Key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yaml"
          target: "docker-compose.yaml"
      - 
        name: Executing docker-compose up -d in server!
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              ls -la
